appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: CjpdQRiBcW/MUoJBIJCLemlOJXaxula60TOflG+meg9uRh1eU5yau5xaiWC5DHZPwvlmW9JJxN/soSiu0tGAClqy006S8wqs6NGw4/lpeFNb7Ws3GIXelxkOaOt6YS+tDkrse3y3QZvFVRS12KTU8Hl4SLAikwPjZnVKu1TzVk03EWoCSdZPBBh4oj2lf93B+0qHgs2gzAyJ2t+gEfLBQPCxFonQ55HgTvaAIz0abeg39w3nsQFSKh7czWckvGE1Waydy2rShCAz6U9FWLJM8waYC3RofHAmno+1npZ6DyH4RIQ0MKMBLknKfur1VxwBzTiLniVBYAu6y6oenDQIUjwTgN0t9RZoyF2fMOwMl8QfZlGLJX6d1mxiDV5iTFmnCBK8SY26Qn1I4Bh9GS5AXi9p2Z+VoDtqgy51CCwBDDv6txWNRErLjDvGJ4ToDul/vhEybbjNyRr+OdNiSVdl2lihQBcth9WNIrq9Sk/OL06mp8g1AO3FXkdiSfbuoRT8zrQyNxpfvTUiT0s5FhFz2nFLR/9oa5TpqY7KT/lVXobn9PU9j2sulRws21vbNIQuqMK/IKkQl1LN1PE1fOyOm06vLDlnWWj9dIM21qwXFD9f8tVAF/PJtIAUo3XScketkU8sEAhHMgj/mqb4BXvpHbnKn7cfcEk79yWCIrszXWU=}
