travis:
  secure:
    BINSTAR_TOKEN: U2n6duwFXTSLcVeoSnsk7uhbFOgzb6EdTdXU2dB8jFyplMJcqPSpSFv9PE9Bcji4w1ZiF2aVCTFdYYuHVM108+G3t2Uml8NbjqURHjm5VcvEWuN9pqdhJXmVTYTSYV2S5cB6lcM5lAmF27t0CsSsUkinSfvOtVEAgcbMwjWAnt/ebstK3c7To7NYjvD7Jf3Ob8fQztM4Uetr0tFaqAJ/n1jdpwKJBoVcINfjKso+TKuByj7fYGkfqT3p/e+w6WI1j8A49fFYvKWc1RKZYP6SbAYDRSsIpo0m22KFofU8LgoSRoyNJBspT4jfKVVvhaA2NjVRojWkKwoe9i0eXWzQf602oZn/lrkuiHmZEJa9WV82EI6lMWJXFy+2Cd6kpQj8P9sqqnhcRNHNm69G7vHT6rZH0sLYLlnsqkpPbZ60gN2jD5VUSVl+6FBPsoUSewWYXZFCG3nvQgeqv/y2qzfu3A+l/NVYkHUJBMkNOm2l4TCfVSI8IuKUOBZOkHhKfEGm2nHXePBUZ7d/S6PbGyFbKKZ25Q76C5JpuUOLdkEOfYVngLmXF9GkGNgK9REMRPchrMK2mIfyVZeruxsaMTH74Qrkl/3OhbP2xWEI8Je7+Hq5apLqLXWjYA2NsUvtZuo+luAn969B3t9+mQrUI+ujVhMWZv84L/Xv+zP90HuAFEA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
